//! Constraint evaluation, connection planning, and diagnostics.
//!
//! This module is intentionally small in v1: the contracts are more important than the algorithms.

use serde::{Deserialize, Serialize};
use serde_json::Value;

use crate::core::{
    Edge, EdgeId, EdgeKind, Graph, Node, NodeId, NodeKindKey, Port, PortCapacity, PortDirection,
    PortId, PortKey, PortKind, SymbolId,
};
use crate::interaction::NodeGraphConnectionMode;
use crate::ops::{EdgeEndpoints, GraphOp};
use crate::types::{TypeCompatibility, TypeCompatibilityResult, TypeDesc};

/// Diagnostic severity.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum DiagnosticSeverity {
    /// Informational note.
    Info,
    /// Warning.
    Warning,
    /// Error.
    Error,
}

/// Diagnostic target.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum DiagnosticTarget {
    /// Graph-level diagnostic.
    Graph,
    /// Node-level diagnostic.
    Node { id: NodeId },
    /// Port-level diagnostic.
    Port { id: PortId },
    /// Edge-level diagnostic.
    Edge { id: EdgeId },
    /// Symbol-level diagnostic.
    Symbol { id: SymbolId },
}

/// A diagnostic produced by validation or connection planning.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Diagnostic {
    /// Stable machine key (for filtering/suppression).
    pub key: String,
    /// Severity.
    pub severity: DiagnosticSeverity,
    /// Target element.
    pub target: DiagnosticTarget,
    /// Human-readable message.
    pub message: String,
    /// Optional suggested fixes expressed as graph ops.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub fixes: Vec<GraphOp>,
}

/// Connection decision.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ConnectDecision {
    /// Accept the connection.
    Accept,
    /// Reject the connection.
    Reject,
}

/// Which endpoint of an existing edge is being reconnected.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum EdgeEndpoint {
    /// The source endpoint (`edge.from`).
    From,
    /// The target endpoint (`edge.to`).
    To,
}

/// A rules-driven plan for connecting two ports.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ConnectPlan {
    /// Decision.
    pub decision: ConnectDecision,
    /// Diagnostics explaining the decision.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub diagnostics: Vec<Diagnostic>,
    /// Optional edits to apply if accepted (disconnect existing edges, insert conversion nodes, etc.).
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub ops: Vec<GraphOp>,
}

impl ConnectPlan {
    /// Creates an accepted plan with no side effects.
    pub fn accept() -> Self {
        Self {
            decision: ConnectDecision::Accept,
            diagnostics: Vec::new(),
            ops: Vec::new(),
        }
    }

    /// Creates a rejected plan with a single error diagnostic.
    pub fn reject(message: impl Into<String>) -> Self {
        Self {
            decision: ConnectDecision::Reject,
            diagnostics: vec![Diagnostic {
                key: "connect.rejected".to_string(),
                severity: DiagnosticSeverity::Error,
                target: DiagnosticTarget::Graph,
                message: message.into(),
                fixes: Vec::new(),
            }],
            ops: Vec::new(),
        }
    }
}

/// Specification for inserting a new node as part of a connection workflow.
///
/// The `ports` list defines the desired UI ordering for the inserted node.
#[derive(Debug, Clone)]
pub struct InsertNodeSpec {
    pub node_id: NodeId,
    pub node: Node,
    pub ports: Vec<(PortId, Port)>,
    pub input: PortId,
    pub output: PortId,
}

/// A template for a port to be instantiated during an insertion workflow.
#[derive(Debug, Clone)]
pub struct PortTemplate {
    pub key: PortKey,
    pub dir: PortDirection,
    pub kind: PortKind,
    pub capacity: PortCapacity,
    pub ty: Option<TypeDesc>,
    pub data: Value,
}

/// A template for inserting a node between two ports.
///
/// This is the preferred UI-to-rules contract: IDs are generated by the rules layer.
#[derive(Debug, Clone)]
pub struct InsertNodeTemplate {
    pub kind: NodeKindKey,
    pub kind_version: u32,
    pub collapsed: bool,
    pub data: Value,
    pub ports: Vec<PortTemplate>,

    /// Which instantiated port should be connected from the upstream edge segment.
    pub input: PortKey,
    /// Which instantiated port should be connected to the downstream edge segment.
    pub output: PortKey,
}

impl InsertNodeTemplate {
    /// Instantiates this template at a given position by allocating fresh IDs.
    pub fn instantiate(&self, at: crate::core::CanvasPoint) -> Result<InsertNodeSpec, String> {
        let node_id = NodeId::new();

        let mut ports: Vec<(PortId, Port)> = Vec::new();
        let mut input: Option<PortId> = None;
        let mut output: Option<PortId> = None;

        for pt in &self.ports {
            let port_id = PortId::new();
            if pt.key == self.input {
                input = Some(port_id);
            }
            if pt.key == self.output {
                output = Some(port_id);
            }

            ports.push((
                port_id,
                Port {
                    node: node_id,
                    key: pt.key.clone(),
                    dir: pt.dir,
                    kind: pt.kind,
                    capacity: pt.capacity,
                    connectable: None,
                    connectable_start: None,
                    connectable_end: None,
                    ty: pt.ty.clone(),
                    data: pt.data.clone(),
                },
            ));
        }

        let Some(input) = input else {
            return Err(format!("template is missing input port: {}", self.input.0));
        };
        let Some(output) = output else {
            return Err(format!(
                "template is missing output port: {}",
                self.output.0
            ));
        };
        if input == output {
            return Err("template input/output ports must be distinct".to_string());
        }

        Ok(InsertNodeSpec {
            node_id,
            node: Node {
                kind: self.kind.clone(),
                kind_version: self.kind_version,
                pos: at,
                selectable: None,
                draggable: None,
                connectable: None,
                deletable: None,
                parent: None,
                extent: None,
                expand_parent: None,
                size: None,
                hidden: false,
                collapsed: self.collapsed,
                ports: Vec::new(),
                data: self.data.clone(),
            },
            ports,
            input,
            output,
        })
    }
}

fn port_kind_for_edge_kind(edge_kind: EdgeKind) -> PortKind {
    match edge_kind {
        EdgeKind::Data => PortKind::Data,
        EdgeKind::Exec => PortKind::Exec,
    }
}

fn edge_kind_for_port_kind(port_kind: PortKind) -> Option<EdgeKind> {
    match port_kind {
        PortKind::Data => Some(EdgeKind::Data),
        PortKind::Exec => Some(EdgeKind::Exec),
    }
}

fn disconnect_for_capacity(
    graph: &Graph,
    edge_kind: EdgeKind,
    from_id: PortId,
    from_capacity: PortCapacity,
    to_id: PortId,
    to_capacity: PortCapacity,
) -> Vec<GraphOp> {
    let mut ops: Vec<GraphOp> = Vec::new();

    if from_capacity == PortCapacity::Single {
        for (edge_id, edge) in graph.edges.iter() {
            if edge.kind == edge_kind && edge.from == from_id {
                ops.push(GraphOp::RemoveEdge {
                    id: *edge_id,
                    edge: edge.clone(),
                });
            }
        }
    }

    if to_capacity == PortCapacity::Single {
        for (edge_id, edge) in graph.edges.iter() {
            if edge.kind == edge_kind && edge.to == to_id {
                ops.push(GraphOp::RemoveEdge {
                    id: *edge_id,
                    edge: edge.clone(),
                });
            }
        }
    }

    ops
}

/// Plans connecting two ports.
///
/// This is a rules-driven decision point used by the UI interaction loop.
/// The returned ops are intended to be applied as part of a single transaction.
pub fn plan_connect_with_mode(
    graph: &Graph,
    a: PortId,
    b: PortId,
    mode: NodeGraphConnectionMode,
) -> ConnectPlan {
    if a == b {
        return ConnectPlan::reject("cannot connect a port to itself");
    }

    let Some(port_a) = graph.ports.get(&a) else {
        return ConnectPlan::reject(format!("missing port: {a:?}"));
    };
    let Some(port_b) = graph.ports.get(&b) else {
        return ConnectPlan::reject(format!("missing port: {b:?}"));
    };

    let (from_id, to_id) = match mode {
        NodeGraphConnectionMode::Strict => match (port_a.dir, port_b.dir) {
            (PortDirection::Out, PortDirection::In) => (a, b),
            (PortDirection::In, PortDirection::Out) => (b, a),
            _ => {
                return ConnectPlan::reject("ports must have opposite directions (in/out)");
            }
        },
        NodeGraphConnectionMode::Loose => match port_a.dir {
            PortDirection::Out => (a, b),
            PortDirection::In => (b, a),
        },
    };

    let Some(from) = graph.ports.get(&from_id) else {
        return ConnectPlan::reject(format!("missing port: {from_id:?}"));
    };
    let Some(to) = graph.ports.get(&to_id) else {
        return ConnectPlan::reject(format!("missing port: {to_id:?}"));
    };

    if from.kind != to.kind {
        return ConnectPlan::reject(format!(
            "port kinds are incompatible: from={:?} to={:?}",
            from.kind, to.kind
        ));
    }

    let edge_kind = match (from.kind, to.kind) {
        (PortKind::Data, PortKind::Data) => EdgeKind::Data,
        (PortKind::Exec, PortKind::Exec) => EdgeKind::Exec,
        _ => {
            return ConnectPlan::reject("port kinds are incompatible");
        }
    };

    for edge in graph.edges.values() {
        if edge.kind == edge_kind && edge.from == from_id && edge.to == to_id {
            return ConnectPlan::accept();
        }
    }

    let mut ops: Vec<GraphOp> =
        disconnect_for_capacity(graph, edge_kind, from_id, from.capacity, to_id, to.capacity);

    ops.push(GraphOp::AddEdge {
        id: EdgeId::new(),
        edge: Edge {
            kind: edge_kind,
            from: from_id,
            to: to_id,
            selectable: None,
            deletable: None,
            reconnectable: None,
        },
    });

    ConnectPlan {
        decision: ConnectDecision::Accept,
        diagnostics: Vec::new(),
        ops,
    }
}

/// Plans connecting two ports (strict mode).
pub fn plan_connect(graph: &Graph, a: PortId, b: PortId) -> ConnectPlan {
    plan_connect_with_mode(graph, a, b, NodeGraphConnectionMode::Strict)
}

/// Plans connecting two ports with optional type compatibility checks.
///
/// If both ports have a resolved type and the edge kind is `Data`, the `compat` policy is used to
/// enforce assignability (`from -> to`).
pub fn plan_connect_typed(
    graph: &Graph,
    a: PortId,
    b: PortId,
    mut type_of: impl FnMut(&Graph, PortId) -> Option<TypeDesc>,
    compat: &mut dyn TypeCompatibility,
) -> ConnectPlan {
    let base = plan_connect(graph, a, b);
    if base.decision != ConnectDecision::Accept {
        return base;
    }

    let Some(port_a) = graph.ports.get(&a) else {
        return ConnectPlan::reject(format!("missing port: {a:?}"));
    };
    let Some(port_b) = graph.ports.get(&b) else {
        return ConnectPlan::reject(format!("missing port: {b:?}"));
    };

    let (from_id, to_id, from, to) = match (port_a.dir, port_b.dir) {
        (PortDirection::Out, PortDirection::In) => (a, b, port_a, port_b),
        (PortDirection::In, PortDirection::Out) => (b, a, port_b, port_a),
        _ => return ConnectPlan::reject("ports must have opposite directions (in/out)"),
    };

    let edge_kind = match (from.kind, to.kind) {
        (PortKind::Data, PortKind::Data) => EdgeKind::Data,
        (PortKind::Exec, PortKind::Exec) => EdgeKind::Exec,
        _ => return ConnectPlan::reject("port kinds are incompatible"),
    };

    if edge_kind != EdgeKind::Data {
        return base;
    }

    let Some(from_ty) = type_of(graph, from_id) else {
        return base;
    };
    let Some(to_ty) = type_of(graph, to_id) else {
        return base;
    };

    match compat.compatible(&from_ty, &to_ty) {
        TypeCompatibilityResult::Compatible => base,
        TypeCompatibilityResult::Incompatible { reason } => ConnectPlan {
            decision: ConnectDecision::Reject,
            diagnostics: vec![Diagnostic {
                key: "connect.type_mismatch".to_string(),
                severity: DiagnosticSeverity::Error,
                target: DiagnosticTarget::Port { id: to_id },
                message: format!("type mismatch: {reason} (from={from_ty:?} to={to_ty:?})"),
                fixes: Vec::new(),
            }],
            ops: Vec::new(),
        },
    }
}

/// Plans connecting two ports by inserting a node between them.
///
/// This is intended for "auto-fix" workflows like inserting a conversion node when types mismatch.
pub fn plan_connect_by_inserting_node(
    graph: &Graph,
    a: PortId,
    b: PortId,
    first_edge_id: EdgeId,
    second_edge_id: EdgeId,
    inserted: InsertNodeSpec,
) -> ConnectPlan {
    let Some(port_a) = graph.ports.get(&a) else {
        return ConnectPlan::reject(format!("missing port: {a:?}"));
    };
    let Some(port_b) = graph.ports.get(&b) else {
        return ConnectPlan::reject(format!("missing port: {b:?}"));
    };

    let (from_id, to_id, from, to) = match (port_a.dir, port_b.dir) {
        (PortDirection::Out, PortDirection::In) => (a, b, port_a, port_b),
        (PortDirection::In, PortDirection::Out) => (b, a, port_b, port_a),
        _ => {
            return ConnectPlan::reject("ports must have opposite directions (in/out)");
        }
    };

    if from.kind != to.kind {
        return ConnectPlan::reject(format!(
            "port kinds are incompatible: from={:?} to={:?}",
            from.kind, to.kind
        ));
    }

    let Some(edge_kind) = edge_kind_for_port_kind(from.kind) else {
        return ConnectPlan::reject("port kinds are incompatible");
    };

    if graph.edges.contains_key(&first_edge_id) {
        return ConnectPlan::reject(format!("edge already exists: {first_edge_id:?}"));
    }
    if graph.edges.contains_key(&second_edge_id) {
        return ConnectPlan::reject(format!("edge already exists: {second_edge_id:?}"));
    }

    if inserted.node_id == from.node || inserted.node_id == to.node {
        return ConnectPlan::reject("inserted node id must be distinct from endpoints");
    }
    if graph.nodes.contains_key(&inserted.node_id) {
        return ConnectPlan::reject(format!("node already exists: {:?}", inserted.node_id));
    }
    for (port_id, _) in &inserted.ports {
        if graph.ports.contains_key(port_id) {
            return ConnectPlan::reject(format!("port already exists: {port_id:?}"));
        }
    }

    if inserted.input == inserted.output {
        return ConnectPlan::reject("inserted input/output ports must be distinct");
    }

    let expected_port_kind = port_kind_for_edge_kind(edge_kind);
    let mut inserted_in: Option<&Port> = None;
    let mut inserted_out: Option<&Port> = None;
    for (port_id, port) in &inserted.ports {
        if port.node != inserted.node_id {
            return ConnectPlan::reject(format!(
                "inserted port has wrong node: port={port_id:?} expected={:?} got={:?}",
                inserted.node_id, port.node
            ));
        }
        if port.kind != expected_port_kind {
            return ConnectPlan::reject(format!(
                "inserted port kind is incompatible: port={port_id:?} kind={:?} expected={:?}",
                port.kind, expected_port_kind
            ));
        }
        if *port_id == inserted.input {
            inserted_in = Some(port);
        }
        if *port_id == inserted.output {
            inserted_out = Some(port);
        }
    }

    let Some(inserted_in) = inserted_in else {
        return ConnectPlan::reject("inserted input port is missing from spec");
    };
    let Some(inserted_out) = inserted_out else {
        return ConnectPlan::reject("inserted output port is missing from spec");
    };

    if inserted_in.dir != PortDirection::In || inserted_out.dir != PortDirection::Out {
        return ConnectPlan::reject("inserted ports must be in -> out");
    }

    let mut ops: Vec<GraphOp> =
        disconnect_for_capacity(graph, edge_kind, from_id, from.capacity, to_id, to.capacity);

    let mut node = inserted.node.clone();
    node.ports = Vec::new();
    ops.push(GraphOp::AddNode {
        id: inserted.node_id,
        node,
    });

    let port_order: Vec<PortId> = inserted.ports.iter().map(|(id, _)| *id).collect();
    for (port_id, port) in inserted.ports {
        ops.push(GraphOp::AddPort { id: port_id, port });
    }
    ops.push(GraphOp::SetNodePorts {
        id: inserted.node_id,
        from: Vec::new(),
        to: port_order,
    });

    ops.push(GraphOp::AddEdge {
        id: first_edge_id,
        edge: Edge {
            kind: edge_kind,
            from: from_id,
            to: inserted.input,
            selectable: None,
            deletable: None,
            reconnectable: None,
        },
    });
    ops.push(GraphOp::AddEdge {
        id: second_edge_id,
        edge: Edge {
            kind: edge_kind,
            from: inserted.output,
            to: to_id,
            selectable: None,
            deletable: None,
            reconnectable: None,
        },
    });

    ConnectPlan {
        decision: ConnectDecision::Accept,
        diagnostics: Vec::new(),
        ops,
    }
}

/// Plans splitting an existing edge by inserting a node (preserving the edge identity for the first segment).
pub fn plan_split_edge_by_inserting_node(
    graph: &Graph,
    edge_id: EdgeId,
    new_edge_id: EdgeId,
    inserted: InsertNodeSpec,
) -> ConnectPlan {
    let Some(edge) = graph.edges.get(&edge_id) else {
        return ConnectPlan::reject(format!("missing edge: {edge_id:?}"));
    };
    if graph.edges.contains_key(&new_edge_id) {
        return ConnectPlan::reject(format!("edge already exists: {new_edge_id:?}"));
    }

    let Some(from_port) = graph.ports.get(&edge.from) else {
        return ConnectPlan::reject("missing edge.from port");
    };
    let Some(to_port) = graph.ports.get(&edge.to) else {
        return ConnectPlan::reject("missing edge.to port");
    };

    if from_port.dir != PortDirection::Out || to_port.dir != PortDirection::In {
        return ConnectPlan::reject("edge must be out -> in");
    }

    let expected_port_kind = port_kind_for_edge_kind(edge.kind);
    if from_port.kind != expected_port_kind || to_port.kind != expected_port_kind {
        return ConnectPlan::reject("edge kind is incompatible with ports");
    }

    if inserted.node_id == from_port.node || inserted.node_id == to_port.node {
        return ConnectPlan::reject("inserted node id must be distinct from endpoints");
    }
    if graph.nodes.contains_key(&inserted.node_id) {
        return ConnectPlan::reject(format!("node already exists: {:?}", inserted.node_id));
    }
    for (port_id, _) in &inserted.ports {
        if graph.ports.contains_key(port_id) {
            return ConnectPlan::reject(format!("port already exists: {port_id:?}"));
        }
    }

    if inserted.input == inserted.output {
        return ConnectPlan::reject("inserted input/output ports must be distinct");
    }

    let mut inserted_in: Option<&Port> = None;
    let mut inserted_out: Option<&Port> = None;
    for (port_id, port) in &inserted.ports {
        if port.node != inserted.node_id {
            return ConnectPlan::reject(format!(
                "inserted port has wrong node: port={port_id:?} expected={:?} got={:?}",
                inserted.node_id, port.node
            ));
        }
        if port.kind != expected_port_kind {
            return ConnectPlan::reject(format!(
                "inserted port kind is incompatible: port={port_id:?} kind={:?} expected={:?}",
                port.kind, expected_port_kind
            ));
        }
        if *port_id == inserted.input {
            inserted_in = Some(port);
        }
        if *port_id == inserted.output {
            inserted_out = Some(port);
        }
    }

    let Some(inserted_in) = inserted_in else {
        return ConnectPlan::reject("inserted input port is missing from spec");
    };
    let Some(inserted_out) = inserted_out else {
        return ConnectPlan::reject("inserted output port is missing from spec");
    };

    if inserted_in.dir != PortDirection::In || inserted_out.dir != PortDirection::Out {
        return ConnectPlan::reject("inserted ports must be in -> out");
    }

    let old = EdgeEndpoints {
        from: edge.from,
        to: edge.to,
    };

    let mut ops: Vec<GraphOp> = Vec::new();

    let mut node = inserted.node.clone();
    node.ports = Vec::new();
    ops.push(GraphOp::AddNode {
        id: inserted.node_id,
        node,
    });

    let port_order: Vec<PortId> = inserted.ports.iter().map(|(id, _)| *id).collect();
    for (port_id, port) in inserted.ports {
        ops.push(GraphOp::AddPort { id: port_id, port });
    }
    ops.push(GraphOp::SetNodePorts {
        id: inserted.node_id,
        from: Vec::new(),
        to: port_order,
    });

    ops.push(GraphOp::SetEdgeEndpoints {
        id: edge_id,
        from: old,
        to: EdgeEndpoints {
            from: edge.from,
            to: inserted.input,
        },
    });
    ops.push(GraphOp::AddEdge {
        id: new_edge_id,
        edge: Edge {
            kind: edge.kind,
            from: inserted.output,
            to: edge.to,
            selectable: edge.selectable,
            deletable: edge.deletable,
            reconnectable: edge.reconnectable,
        },
    });

    ConnectPlan {
        decision: ConnectDecision::Accept,
        diagnostics: Vec::new(),
        ops,
    }
}

/// Plans reconnecting one endpoint of an existing edge to a new port.
///
/// This is used for "yank and reattach" workflows where edge identity should be preserved.
pub fn plan_reconnect_edge_with_mode(
    graph: &Graph,
    edge_id: EdgeId,
    endpoint: EdgeEndpoint,
    new_port: PortId,
    mode: NodeGraphConnectionMode,
) -> ConnectPlan {
    let Some(edge) = graph.edges.get(&edge_id) else {
        return ConnectPlan::reject(format!("missing edge: {edge_id:?}"));
    };

    let old = EdgeEndpoints {
        from: edge.from,
        to: edge.to,
    };

    let (candidate_from, candidate_to) = match endpoint {
        EdgeEndpoint::From => (new_port, edge.to),
        EdgeEndpoint::To => (edge.from, new_port),
    };

    if candidate_from == candidate_to {
        return ConnectPlan::reject("cannot connect a port to itself");
    }

    if candidate_from == old.from && candidate_to == old.to {
        return ConnectPlan::accept();
    }

    let Some(from) = graph.ports.get(&candidate_from) else {
        return ConnectPlan::reject(format!("missing port: {candidate_from:?}"));
    };
    let Some(to) = graph.ports.get(&candidate_to) else {
        return ConnectPlan::reject(format!("missing port: {candidate_to:?}"));
    };

    if mode == NodeGraphConnectionMode::Strict
        && (from.dir != PortDirection::Out || to.dir != PortDirection::In)
    {
        return ConnectPlan::reject("ports must be out -> in for reconnection");
    }

    if from.kind != to.kind {
        return ConnectPlan::reject(format!(
            "port kinds are incompatible: from={:?} to={:?}",
            from.kind, to.kind
        ));
    }

    let expected_edge_kind = match (from.kind, to.kind) {
        (PortKind::Data, PortKind::Data) => EdgeKind::Data,
        (PortKind::Exec, PortKind::Exec) => EdgeKind::Exec,
        _ => {
            return ConnectPlan::reject("port kinds are incompatible");
        }
    };

    if edge.kind != expected_edge_kind {
        return ConnectPlan::reject(format!(
            "edge kind is incompatible with ports: edge={:?} expected={:?}",
            edge.kind, expected_edge_kind
        ));
    }

    for (other_id, other) in &graph.edges {
        if *other_id == edge_id {
            continue;
        }
        if other.kind == edge.kind && other.from == candidate_from && other.to == candidate_to {
            return ConnectPlan::reject("duplicate connection already exists");
        }
    }

    let mut ops: Vec<GraphOp> = Vec::new();

    if from.capacity == PortCapacity::Single {
        for (other_id, other) in &graph.edges {
            if *other_id == edge_id {
                continue;
            }
            if other.kind == edge.kind && other.from == candidate_from {
                ops.push(GraphOp::RemoveEdge {
                    id: *other_id,
                    edge: other.clone(),
                });
            }
        }
    }

    if to.capacity == PortCapacity::Single {
        for (other_id, other) in &graph.edges {
            if *other_id == edge_id {
                continue;
            }
            if other.kind == edge.kind && other.to == candidate_to {
                ops.push(GraphOp::RemoveEdge {
                    id: *other_id,
                    edge: other.clone(),
                });
            }
        }
    }

    ops.push(GraphOp::SetEdgeEndpoints {
        id: edge_id,
        from: old,
        to: EdgeEndpoints {
            from: candidate_from,
            to: candidate_to,
        },
    });

    ConnectPlan {
        decision: ConnectDecision::Accept,
        diagnostics: Vec::new(),
        ops,
    }
}

/// Plans reconnecting one endpoint of an existing edge (strict mode).
pub fn plan_reconnect_edge(
    graph: &Graph,
    edge_id: EdgeId,
    endpoint: EdgeEndpoint,
    new_port: PortId,
) -> ConnectPlan {
    plan_reconnect_edge_with_mode(
        graph,
        edge_id,
        endpoint,
        new_port,
        NodeGraphConnectionMode::Strict,
    )
}

#[cfg(test)]
mod tests;
