//! Constraint evaluation, connection planning, and diagnostics.
//!
//! This module is intentionally small in v1: the contracts are more important than the algorithms.

use serde::{Deserialize, Serialize};
use serde_json::Value;

use jellyflow_core::core::{
    EdgeId, Node, NodeId, NodeKindKey, Port, PortCapacity, PortDirection, PortId, PortKey,
    PortKind, SymbolId,
};
use jellyflow_core::ops::GraphOp;
use jellyflow_core::types::TypeDesc;

/// Diagnostic severity.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum DiagnosticSeverity {
    /// Informational note.
    Info,
    /// Warning.
    Warning,
    /// Error.
    Error,
}

/// Diagnostic target.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum DiagnosticTarget {
    /// Graph-level diagnostic.
    Graph,
    /// Node-level diagnostic.
    Node { id: NodeId },
    /// Port-level diagnostic.
    Port { id: PortId },
    /// Edge-level diagnostic.
    Edge { id: EdgeId },
    /// Symbol-level diagnostic.
    Symbol { id: SymbolId },
}

/// A diagnostic produced by validation or connection planning.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Diagnostic {
    /// Stable machine key (for filtering/suppression).
    pub key: String,
    /// Severity.
    pub severity: DiagnosticSeverity,
    /// Target element.
    pub target: DiagnosticTarget,
    /// Human-readable message.
    pub message: String,
    /// Optional suggested fixes expressed as graph ops.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub fixes: Vec<GraphOp>,
}

/// Connection decision.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ConnectDecision {
    /// Accept the connection.
    Accept,
    /// Reject the connection.
    Reject,
}

/// Which endpoint of an existing edge is being reconnected.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum EdgeEndpoint {
    /// The source endpoint (`edge.from`).
    From,
    /// The target endpoint (`edge.to`).
    To,
}

/// A rules-driven plan for connecting two ports.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ConnectPlan {
    /// Decision.
    pub decision: ConnectDecision,
    /// Diagnostics explaining the decision.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub diagnostics: Vec<Diagnostic>,
    /// Optional edits to apply if accepted (disconnect existing edges, insert conversion nodes, etc.).
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub ops: Vec<GraphOp>,
}

impl ConnectPlan {
    /// Creates an accepted plan with no side effects.
    pub fn accept() -> Self {
        Self {
            decision: ConnectDecision::Accept,
            diagnostics: Vec::new(),
            ops: Vec::new(),
        }
    }

    /// Creates a rejected plan with a single error diagnostic.
    pub fn reject(message: impl Into<String>) -> Self {
        Self {
            decision: ConnectDecision::Reject,
            diagnostics: vec![Diagnostic {
                key: "connect.rejected".to_string(),
                severity: DiagnosticSeverity::Error,
                target: DiagnosticTarget::Graph,
                message: message.into(),
                fixes: Vec::new(),
            }],
            ops: Vec::new(),
        }
    }
}

/// Specification for inserting a new node as part of a connection workflow.
///
/// The `ports` list defines the desired UI ordering for the inserted node.
#[derive(Debug, Clone)]
pub struct InsertNodeSpec {
    pub node_id: NodeId,
    pub node: Node,
    pub ports: Vec<(PortId, Port)>,
    pub input: PortId,
    pub output: PortId,
}

/// A template for a port to be instantiated during an insertion workflow.
#[derive(Debug, Clone)]
pub struct PortTemplate {
    pub key: PortKey,
    pub dir: PortDirection,
    pub kind: PortKind,
    pub capacity: PortCapacity,
    pub ty: Option<TypeDesc>,
    pub data: Value,
}

/// A template for inserting a node between two ports.
///
/// This is the preferred UI-to-rules contract: IDs are generated by the rules layer.
#[derive(Debug, Clone)]
pub struct InsertNodeTemplate {
    pub kind: NodeKindKey,
    pub kind_version: u32,
    pub collapsed: bool,
    pub data: Value,
    pub ports: Vec<PortTemplate>,

    /// Which instantiated port should be connected from the upstream edge segment.
    pub input: PortKey,
    /// Which instantiated port should be connected to the downstream edge segment.
    pub output: PortKey,
}

impl InsertNodeTemplate {
    /// Instantiates this template at a given position by allocating fresh IDs.
    pub fn instantiate(
        &self,
        at: jellyflow_core::core::CanvasPoint,
    ) -> Result<InsertNodeSpec, String> {
        let node_id = NodeId::new();

        let mut ports: Vec<(PortId, Port)> = Vec::new();
        let mut input: Option<PortId> = None;
        let mut output: Option<PortId> = None;

        for pt in &self.ports {
            let port_id = PortId::new();
            if pt.key == self.input {
                input = Some(port_id);
            }
            if pt.key == self.output {
                output = Some(port_id);
            }

            ports.push((
                port_id,
                Port {
                    node: node_id,
                    key: pt.key.clone(),
                    dir: pt.dir,
                    kind: pt.kind,
                    capacity: pt.capacity,
                    connectable: None,
                    connectable_start: None,
                    connectable_end: None,
                    ty: pt.ty.clone(),
                    data: pt.data.clone(),
                },
            ));
        }

        let Some(input) = input else {
            return Err(format!("template is missing input port: {}", self.input.0));
        };
        let Some(output) = output else {
            return Err(format!(
                "template is missing output port: {}",
                self.output.0
            ));
        };
        if input == output {
            return Err("template input/output ports must be distinct".to_string());
        }

        Ok(InsertNodeSpec {
            node_id,
            node: Node {
                kind: self.kind.clone(),
                kind_version: self.kind_version,
                pos: at,
                selectable: None,
                draggable: None,
                connectable: None,
                deletable: None,
                parent: None,
                extent: None,
                expand_parent: None,
                size: None,
                hidden: false,
                collapsed: self.collapsed,
                ports: Vec::new(),
                data: self.data.clone(),
            },
            ports,
            input,
            output,
        })
    }
}

mod connection;

pub use connection::{
    plan_connect, plan_connect_by_inserting_node, plan_connect_by_inserting_node_with_policy,
    plan_connect_typed, plan_connect_typed_with_mode_and_policy, plan_connect_typed_with_policy,
    plan_connect_with_mode, plan_connect_with_mode_and_policy, plan_reconnect_edge,
    plan_reconnect_edge_with_mode, plan_reconnect_edge_with_mode_and_policy,
    plan_split_edge_by_inserting_node,
};

#[cfg(test)]
mod tests;
