use serde_json::Value;

use jellyflow_core::core::{
    CanvasPoint, Node, NodeId, NodeKindKey, Port, PortCapacity, PortDirection, PortId, PortKey,
    PortKind,
};
use jellyflow_core::types::TypeDesc;

/// Specification for inserting a new node as part of a connection workflow.
///
/// The `ports` list defines the desired UI ordering for the inserted node.
#[derive(Debug, Clone)]
pub struct InsertNodeSpec {
    pub node_id: NodeId,
    pub node: Node,
    pub ports: Vec<(PortId, Port)>,
    pub input: PortId,
    pub output: PortId,
}

/// A template for a port to be instantiated during an insertion workflow.
#[derive(Debug, Clone)]
pub struct PortTemplate {
    pub key: PortKey,
    pub dir: PortDirection,
    pub kind: PortKind,
    pub capacity: PortCapacity,
    pub ty: Option<TypeDesc>,
    pub data: Value,
}

/// A template for inserting a node between two ports.
///
/// This is the preferred UI-to-rules contract: IDs are generated by the rules layer.
#[derive(Debug, Clone)]
pub struct InsertNodeTemplate {
    pub kind: NodeKindKey,
    pub kind_version: u32,
    pub collapsed: bool,
    pub data: Value,
    pub ports: Vec<PortTemplate>,

    /// Which instantiated port should be connected from the upstream edge segment.
    pub input: PortKey,
    /// Which instantiated port should be connected to the downstream edge segment.
    pub output: PortKey,
}

impl InsertNodeTemplate {
    /// Instantiates this template at a given position by allocating fresh IDs.
    pub fn instantiate(&self, at: CanvasPoint) -> Result<InsertNodeSpec, String> {
        let node_id = NodeId::new();

        let mut ports: Vec<(PortId, Port)> = Vec::new();
        let mut input: Option<PortId> = None;
        let mut output: Option<PortId> = None;

        for pt in &self.ports {
            let port_id = PortId::new();
            if pt.key == self.input {
                input = Some(port_id);
            }
            if pt.key == self.output {
                output = Some(port_id);
            }

            ports.push((
                port_id,
                Port {
                    node: node_id,
                    key: pt.key.clone(),
                    dir: pt.dir,
                    kind: pt.kind,
                    capacity: pt.capacity,
                    connectable: None,
                    connectable_start: None,
                    connectable_end: None,
                    ty: pt.ty.clone(),
                    data: pt.data.clone(),
                },
            ));
        }

        let Some(input) = input else {
            return Err(format!("template is missing input port: {}", self.input.0));
        };
        let Some(output) = output else {
            return Err(format!(
                "template is missing output port: {}",
                self.output.0
            ));
        };
        if input == output {
            return Err("template input/output ports must be distinct".to_string());
        }

        Ok(InsertNodeSpec {
            node_id,
            node: Node {
                kind: self.kind.clone(),
                kind_version: self.kind_version,
                pos: at,
                selectable: None,
                draggable: None,
                connectable: None,
                deletable: None,
                parent: None,
                extent: None,
                expand_parent: None,
                size: None,
                hidden: false,
                collapsed: self.collapsed,
                ports: Vec::new(),
                data: self.data.clone(),
            },
            ports,
            input,
            output,
        })
    }
}
