use serde::{Deserialize, Serialize};

use jellyflow_core::core::{CanvasRect, CanvasSize};
use jellyflow_core::interaction::{
    NodeGraphConnectionMode, NodeGraphDragHandleMode, NodeGraphModifierKey,
    NodeGraphZoomActivationKey,
};

use crate::io::tuning::{
    NodeGraphAutoPanTuning, NodeGraphPaintCachePruneTuning, NodeGraphPanInertiaTuning,
    NodeGraphRuntimeTuning, NodeGraphSpatialIndexTuning, default_only_render_visible_elements,
};

use super::defaults::*;
use super::interaction::NodeGraphInteractionConfig;
use super::keys::{NodeGraphDeleteKey, NodeGraphKeyCode};
use super::types::{
    NodeGraphBoxSelectEdges, NodeGraphNodeOrigin, NodeGraphNudgeStepMode,
    NodeGraphPanOnDragButtons, NodeGraphPanOnScrollMode, NodeGraphSelectionMode,
    NodeGraphViewportEase, NodeGraphViewportInterpolate, default_box_select_edges,
    default_pan_on_drag_buttons,
};

/// Resolved runtime interaction state assembled from persisted config and runtime tuning.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct NodeGraphInteractionState {
    pub elements_selectable: bool,
    pub nodes_draggable: bool,
    pub nodes_connectable: bool,
    pub nodes_deletable: bool,
    pub edges_selectable: bool,
    pub edges_deletable: bool,
    pub edges_focusable: bool,
    pub edges_reconnectable: bool,
    pub connection_mode: NodeGraphConnectionMode,
    pub connection_radius: f32,
    pub reconnect_radius: f32,
    pub reconnect_on_drop_empty: bool,
    pub edge_interaction_width: f32,
    pub bezier_hit_test_steps: u8,
    pub spatial_index: NodeGraphSpatialIndexTuning,
    pub only_render_visible_elements: bool,
    pub elevate_nodes_on_select: bool,
    pub elevate_edges_on_select: bool,
    pub paint_cache_prune: NodeGraphPaintCachePruneTuning,
    pub snap_to_grid: bool,
    pub snap_grid: CanvasSize,
    pub snaplines: bool,
    pub snaplines_threshold: f32,
    pub pan_on_scroll: bool,
    pub pan_on_drag: NodeGraphPanOnDragButtons,
    pub selection_on_drag: bool,
    pub selection_mode: NodeGraphSelectionMode,
    pub box_select_edges: NodeGraphBoxSelectEdges,
    pub selection_key: NodeGraphModifierKey,
    pub multi_selection_key: NodeGraphModifierKey,
    pub delete_key: NodeGraphDeleteKey,
    pub nudge_step_mode: NodeGraphNudgeStepMode,
    pub nudge_step_px: f32,
    pub nudge_fast_step_px: f32,
    pub disable_keyboard_a11y: bool,
    pub pane_click_distance: f32,
    pub pan_activation_key_code: Option<NodeGraphKeyCode>,
    pub space_to_pan: bool,
    pub pan_on_scroll_speed: f32,
    pub pan_on_scroll_mode: NodeGraphPanOnScrollMode,
    pub pan_inertia: NodeGraphPanInertiaTuning,
    pub zoom_on_scroll: bool,
    pub zoom_on_scroll_speed: f32,
    pub zoom_on_pinch: bool,
    pub zoom_on_pinch_speed: f32,
    pub zoom_on_double_click: bool,
    pub frame_view_duration_ms: u32,
    pub frame_view_interpolate: NodeGraphViewportInterpolate,
    pub frame_view_ease: Option<NodeGraphViewportEase>,
    pub frame_view_padding: f32,
    pub reroute_on_edge_double_click: bool,
    pub edge_insert_on_alt_drag: bool,
    pub zoom_activation_key: NodeGraphZoomActivationKey,
    pub node_drag_threshold: f32,
    pub node_drag_handle_mode: NodeGraphDragHandleMode,
    pub node_click_distance: f32,
    pub connection_drag_threshold: f32,
    pub connect_on_click: bool,
    pub auto_pan: NodeGraphAutoPanTuning,
    pub translate_extent: Option<CanvasRect>,
    pub node_extent: Option<CanvasRect>,
    pub node_origin: NodeGraphNodeOrigin,
}

impl NodeGraphInteractionState {
    pub fn from_parts(
        config: &NodeGraphInteractionConfig,
        runtime_tuning: &NodeGraphRuntimeTuning,
    ) -> Self {
        Self {
            elements_selectable: config.elements_selectable,
            nodes_draggable: config.nodes_draggable,
            nodes_connectable: config.nodes_connectable,
            nodes_deletable: config.nodes_deletable,
            edges_selectable: config.edges_selectable,
            edges_deletable: config.edges_deletable,
            edges_focusable: config.edges_focusable,
            edges_reconnectable: config.edges_reconnectable,
            connection_mode: config.connection_mode,
            connection_radius: config.connection_radius,
            reconnect_radius: config.reconnect_radius,
            reconnect_on_drop_empty: config.reconnect_on_drop_empty,
            edge_interaction_width: config.edge_interaction_width,
            bezier_hit_test_steps: config.bezier_hit_test_steps,
            spatial_index: runtime_tuning.spatial_index,
            only_render_visible_elements: runtime_tuning.only_render_visible_elements,
            elevate_nodes_on_select: config.elevate_nodes_on_select,
            elevate_edges_on_select: config.elevate_edges_on_select,
            paint_cache_prune: runtime_tuning.paint_cache_prune,
            snap_to_grid: config.snap_to_grid,
            snap_grid: config.snap_grid,
            snaplines: config.snaplines,
            snaplines_threshold: config.snaplines_threshold,
            pan_on_scroll: config.pan_on_scroll,
            pan_on_drag: config.pan_on_drag,
            selection_on_drag: config.selection_on_drag,
            selection_mode: config.selection_mode,
            box_select_edges: config.box_select_edges,
            selection_key: config.selection_key,
            multi_selection_key: config.multi_selection_key,
            delete_key: config.delete_key,
            nudge_step_mode: config.nudge_step_mode,
            nudge_step_px: config.nudge_step_px,
            nudge_fast_step_px: config.nudge_fast_step_px,
            disable_keyboard_a11y: config.disable_keyboard_a11y,
            pane_click_distance: config.pane_click_distance,
            pan_activation_key_code: config.pan_activation_key_code,
            space_to_pan: config.space_to_pan,
            pan_on_scroll_speed: config.pan_on_scroll_speed,
            pan_on_scroll_mode: config.pan_on_scroll_mode,
            pan_inertia: config.pan_inertia.clone(),
            zoom_on_scroll: config.zoom_on_scroll,
            zoom_on_scroll_speed: config.zoom_on_scroll_speed,
            zoom_on_pinch: config.zoom_on_pinch,
            zoom_on_pinch_speed: config.zoom_on_pinch_speed,
            zoom_on_double_click: config.zoom_on_double_click,
            frame_view_duration_ms: config.frame_view_duration_ms,
            frame_view_interpolate: config.frame_view_interpolate,
            frame_view_ease: config.frame_view_ease,
            frame_view_padding: config.frame_view_padding,
            reroute_on_edge_double_click: config.reroute_on_edge_double_click,
            edge_insert_on_alt_drag: config.edge_insert_on_alt_drag,
            zoom_activation_key: config.zoom_activation_key,
            node_drag_threshold: config.node_drag_threshold,
            node_drag_handle_mode: config.node_drag_handle_mode,
            node_click_distance: config.node_click_distance,
            connection_drag_threshold: config.connection_drag_threshold,
            connect_on_click: config.connect_on_click,
            auto_pan: config.auto_pan.clone(),
            translate_extent: config.translate_extent,
            node_extent: config.node_extent,
            node_origin: config.node_origin,
        }
    }

    pub fn config(&self) -> NodeGraphInteractionConfig {
        NodeGraphInteractionConfig {
            elements_selectable: self.elements_selectable,
            nodes_draggable: self.nodes_draggable,
            nodes_connectable: self.nodes_connectable,
            nodes_deletable: self.nodes_deletable,
            edges_selectable: self.edges_selectable,
            edges_deletable: self.edges_deletable,
            edges_focusable: self.edges_focusable,
            edges_reconnectable: self.edges_reconnectable,
            connection_mode: self.connection_mode,
            connection_radius: self.connection_radius,
            reconnect_radius: self.reconnect_radius,
            reconnect_on_drop_empty: self.reconnect_on_drop_empty,
            edge_interaction_width: self.edge_interaction_width,
            bezier_hit_test_steps: self.bezier_hit_test_steps,
            elevate_nodes_on_select: self.elevate_nodes_on_select,
            elevate_edges_on_select: self.elevate_edges_on_select,
            snap_to_grid: self.snap_to_grid,
            snap_grid: self.snap_grid,
            snaplines: self.snaplines,
            snaplines_threshold: self.snaplines_threshold,
            pan_on_scroll: self.pan_on_scroll,
            pan_on_drag: self.pan_on_drag,
            selection_on_drag: self.selection_on_drag,
            selection_mode: self.selection_mode,
            box_select_edges: self.box_select_edges,
            selection_key: self.selection_key,
            multi_selection_key: self.multi_selection_key,
            delete_key: self.delete_key,
            nudge_step_mode: self.nudge_step_mode,
            nudge_step_px: self.nudge_step_px,
            nudge_fast_step_px: self.nudge_fast_step_px,
            disable_keyboard_a11y: self.disable_keyboard_a11y,
            pane_click_distance: self.pane_click_distance,
            pan_activation_key_code: self.pan_activation_key_code,
            space_to_pan: self.space_to_pan,
            pan_on_scroll_speed: self.pan_on_scroll_speed,
            pan_on_scroll_mode: self.pan_on_scroll_mode,
            pan_inertia: self.pan_inertia.clone(),
            zoom_on_scroll: self.zoom_on_scroll,
            zoom_on_scroll_speed: self.zoom_on_scroll_speed,
            zoom_on_pinch: self.zoom_on_pinch,
            zoom_on_pinch_speed: self.zoom_on_pinch_speed,
            zoom_on_double_click: self.zoom_on_double_click,
            frame_view_duration_ms: self.frame_view_duration_ms,
            frame_view_interpolate: self.frame_view_interpolate,
            frame_view_ease: self.frame_view_ease,
            frame_view_padding: self.frame_view_padding,
            reroute_on_edge_double_click: self.reroute_on_edge_double_click,
            edge_insert_on_alt_drag: self.edge_insert_on_alt_drag,
            zoom_activation_key: self.zoom_activation_key,
            node_drag_threshold: self.node_drag_threshold,
            node_drag_handle_mode: self.node_drag_handle_mode,
            node_click_distance: self.node_click_distance,
            connection_drag_threshold: self.connection_drag_threshold,
            connect_on_click: self.connect_on_click,
            auto_pan: self.auto_pan.clone(),
            translate_extent: self.translate_extent,
            node_extent: self.node_extent,
            node_origin: self.node_origin,
        }
    }

    pub fn runtime_tuning(&self) -> NodeGraphRuntimeTuning {
        NodeGraphRuntimeTuning {
            spatial_index: self.spatial_index,
            only_render_visible_elements: self.only_render_visible_elements,
            paint_cache_prune: self.paint_cache_prune,
        }
    }

    pub fn split(&self) -> (NodeGraphInteractionConfig, NodeGraphRuntimeTuning) {
        (self.config(), self.runtime_tuning())
    }
}

impl Default for NodeGraphInteractionState {
    fn default() -> Self {
        Self {
            elements_selectable: default_elements_selectable(),
            nodes_draggable: default_nodes_draggable(),
            nodes_connectable: default_nodes_connectable(),
            nodes_deletable: default_nodes_deletable(),
            edges_selectable: default_edges_selectable(),
            edges_deletable: default_edges_deletable(),
            edges_focusable: default_edges_focusable(),
            edges_reconnectable: default_edges_reconnectable(),
            connection_mode: NodeGraphConnectionMode::default(),
            connection_radius: default_connection_radius(),
            reconnect_radius: default_reconnect_radius(),
            reconnect_on_drop_empty: false,
            edge_interaction_width: default_edge_interaction_width(),
            bezier_hit_test_steps: default_bezier_hit_test_steps(),
            spatial_index: NodeGraphSpatialIndexTuning::default(),
            only_render_visible_elements: default_only_render_visible_elements(),
            elevate_nodes_on_select: default_elevate_nodes_on_select(),
            elevate_edges_on_select: default_elevate_edges_on_select(),
            paint_cache_prune: NodeGraphPaintCachePruneTuning::default(),
            snap_to_grid: false,
            snap_grid: default_snap_grid(),
            snaplines: default_snaplines(),
            snaplines_threshold: default_snaplines_threshold(),
            pan_on_scroll: default_pan_on_scroll(),
            pan_on_drag: default_pan_on_drag_buttons(),
            selection_on_drag: false,
            selection_mode: NodeGraphSelectionMode::default(),
            box_select_edges: default_box_select_edges(),
            selection_key: default_selection_key(),
            multi_selection_key: default_multi_selection_key(),
            delete_key: NodeGraphDeleteKey::default(),
            nudge_step_mode: NodeGraphNudgeStepMode::default(),
            nudge_step_px: default_nudge_step_px(),
            nudge_fast_step_px: default_nudge_fast_step_px(),
            disable_keyboard_a11y: false,
            pane_click_distance: default_pane_click_distance(),
            pan_activation_key_code: default_pan_activation_key_code(),
            space_to_pan: default_space_to_pan(),
            pan_on_scroll_speed: default_pan_on_scroll_speed(),
            pan_on_scroll_mode: NodeGraphPanOnScrollMode::default(),
            pan_inertia: NodeGraphPanInertiaTuning::default(),
            zoom_on_scroll: default_zoom_on_scroll(),
            zoom_on_scroll_speed: default_zoom_on_scroll_speed(),
            zoom_on_pinch: default_zoom_on_pinch(),
            zoom_on_pinch_speed: default_zoom_on_pinch_speed(),
            zoom_on_double_click: default_zoom_on_double_click(),
            frame_view_duration_ms: default_frame_view_duration_ms(),
            frame_view_interpolate: NodeGraphViewportInterpolate::default(),
            frame_view_ease: None,
            frame_view_padding: default_frame_view_padding(),
            reroute_on_edge_double_click: default_reroute_on_edge_double_click(),
            edge_insert_on_alt_drag: default_edge_insert_on_alt_drag(),
            zoom_activation_key: NodeGraphZoomActivationKey::default(),
            node_drag_threshold: default_node_drag_threshold(),
            node_drag_handle_mode: NodeGraphDragHandleMode::default(),
            node_click_distance: default_node_click_distance(),
            connection_drag_threshold: default_connection_drag_threshold(),
            connect_on_click: false,
            auto_pan: NodeGraphAutoPanTuning::default(),
            translate_extent: None,
            node_extent: None,
            node_origin: NodeGraphNodeOrigin::default(),
        }
    }
}
